version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: storedb
    ports:
      - "5432:5432"  
  app:
    image: ms-store
    ports:
      - 13000:3000
      